source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

platform :ios, '8.0'
target ‘Weibo_Object-C’ do

pod 'YYWebImage'
pod 'AFNetworking'
pod 'Masonry'
pod 'FMDB'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'YYModel'
#pod 'Reveal-iOS-SDK', :configurations => ['Debug']
#pod 'Bugly'
pod 'SDWebImage'
pod 'pop'
pod 'AlicloudMAN', '~> 1.0.12'


end
