source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target ‘Weibo_Object-C’ do

pod 'YYWebImage'
pod 'AFNetworking'
pod 'Masonry'
pod 'FMDB'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'YYModel'
pod 'Reveal-iOS-SDK', :configurations => ['Debug']
pod 'Bugly'
pod 'FMDB'

end
