source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target ‘Weibo_Object-C’ do

pod 'SDWebImage','~> 3.7.3'
pod 'AFNetworking', '~> 3.0.4'
pod 'Masonry', '~> 0.6.3'
pod 'PureLayout', '~> 3.0.1'
pod 'FMDB', '~> 2.6.2'
pod 'MJRefresh', '~> 3.1.1'
pod 'TPKeyboardAvoiding', '~> 1.3'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'Mantle', '~> 2.0.7'
pod 'MMDrawerController', '~> 0.5.7'

end
